GetIT 과 Injectable 을 이용한 DI 보일러 플레이트 코드 작성 완료
L1A-crew/zzekak_client pull request #5
Opened 2023-12-16 11:14 UTC by WongueShin

## AS IS:
zzekak 클라이언트는 DI 를 할 수 있는 코드가 존재 하지 않았습니다.

## TO BE:
GetIt 과 Injectable 을 이용해 멀티모듈에서 원활히 DI 를 할 수 있는지 확인하고, 추후 작성시 도움이 될 보일러 플레이트 코드를 작성합니다.

2023-12-16 11:15 UTC, WongueShin commented
@howyoujini 
http client 를 구축 할 때 참고하세요.
일부로 도움이 될 수 있도록 async DI 로 테스트하였습니다.

2023-12-19 17:28 UTC, howyoujini requested changes
조금만 확인해주세용~

2023-12-19 17:28 UTC, howyoujini commented on app/lib/home/v_home.dart
> +  User? user;
만약 initstate 에서 받아오지 못하거나, null 값을 줄 때에도
사용자 화면에 null 이라고 뜨겠네요! 요것도 잘 처리하면 좋을 것 같습니다.. (비록 작고 매우 디테일이지만)

2023-12-19 17:28 UTC, howyoujini commented on app/lib/main.dart
> +late final GetIt getIt;
getIt 을 late 로 받아도 문제없겠죠? 메인은 반드시 부를테니까..?

2023-12-19 17:28 UTC, howyoujini commented on core/lib/model/identifier/identifier.dart
> +final class Identifier {
오 class 앞에 final 을 붙일수가 있네요......

2023-12-19 17:28 UTC, howyoujini commented on core/lib/model/identifier/identifier.dart
> +    if (other is! Identifier) return false;
좋아요~

2023-12-19 17:28 UTC, howyoujini commented on core/lib/model/representable/representable.dart
> +  String represent() => _nickName;
getter 로 가져온다면, nickname 을 변수로 가져올 수 있을 것 같습니다..!
혹은 represent() 함수가 해야하는 일이 더 있는 것일까요? 
'표현한다'라는 이름에서는 '닉네임'뿐만 아니라 더 많은 일을 할 것 같네요~

2023-12-19 17:28 UTC, howyoujini commented on app/lib/home/v_home.dart
> +  final UserRepository userRepository = GetIt.instance<UserRepository>();
앞으로, 스크린마다 repository 를 선언해야 할까요?

2023-12-19 17:28 UTC, howyoujini commented on data/lib/di/data_di_config.dart
> +GetIt getIt = GetIt.instance;
이렇게 바로 쓸 수가 있나요? 신기하네요!

2023-12-19 17:29 UTC, howyoujini commented on data/lib/di/data_di_config.dart
> +GetIt getIt = GetIt.instance;
getIt 의 Global ServiceLocator 이네요

2023-12-20 12:47 UTC, WongueShin commented on core/lib/model/identifier/identifier.dart
> +final class Identifier {
https://dart.dev/language/class-modifiers#final
더 이상 확장을 막을 수 있는 클래스 키워드랍니다.

2023-12-21 09:01 UTC, WongueShin commented
구두로 관련사항을 다 협의했기 때문에, 병합합니다.

2023-12-21 09:01 UTC, merged