Asset 관리 Codegen 빌드 스크립트 + 커스텀 린트 작성
L1A-crew/zzekak_client pull request #6
Opened 2023-12-18 14:37 UTC by WongueShin

이전에는 Asset 을 String 리터럴로 관리하였기 떄문에 오타, 파일 이동, 이름 변경등에 취약했습니다.

이제 이를 Codegen 되는 Script 로 관리 하고, Image.asset() 혹슨 SvgImage.asset() 의 생성자 함수 호출시,
바로 String 리터럴를 주입 할 때 lint Warn 을 내 관리 할 수 있도록 커스텀 린트를 같이 작업 하였습니다.

2023-12-19 17:40 UTC, howyoujini requested changes
이전 PR 확인후, 이 PR 확인 부탁드립니다 :)
작성하시느라 너무 수고하셨어요~

2023-12-19 17:40 UTC, howyoujini commented on app/asset_management_script.dart
> +    final assetsDirectory = Directory('${scriptLocationDir.path}/assets');
`scriptLocationDir.path` 이것도 static string 으로 뺄 수 있을 것 같네요!

2023-12-19 17:40 UTC, howyoujini commented on app/asset_management_script.dart
> +    // 'gen' 디렉토리가 없는 경우 생성
주석 감사합니다 :)

2023-12-19 17:40 UTC, howyoujini commented on app/asset_management_script.dart
> +    exit(1);
컴파일단계에서 어차피 한번 qa 를 통해 검증할 테니까.. 유저 앱이 강제종료가 될 경우는 없겠죠? 없을듯!

2023-12-19 17:40 UTC, howyoujini commented on app/asset_management_script.dart
> +      genDirectory.createSync();
제가 이 부분은 사용을 해보지 않아서, 잘 모르는 함수이지만..
existsSync() 와 createSync(), deleteSync() 등

위 함수들이 비동기처리를 해야하는 함수들은 아니죠?

2023-12-19 17:41 UTC, howyoujini commented on app/asset_management_script.dart
> +      genDirectory.createSync();
함수 이름처럼 말그대로 sync 라 처리해줄 필요는 없어보이지만
혹시나 여쭤봅니다!

2023-12-24 05:52 UTC, WongueShin commented
구두 협의 후, 모든 사항에 대한 논의가 끝났으므로 PR 을 병합합니다!

2023-12-24 05:52 UTC, merged